# Use an official JDK 17 runtime as a parent image
FROM openjdk:17

## Set the working directory
#WORKDIR /dlb-user
#
## Copy the Gradle wrapper and the gradle directory
#COPY gradlew .
#COPY gradle /dlb-user/gradle
#
## Copy the rest of the application code
#COPY . .
#
## Give execute permission for the gradlew script
#RUN chmod +x ./gradlew
#
## Build the application
#RUN ./gradlew build

# Expose the port the application will run on
EXPOSE 8080

# The application's JAR file (this should match the JAR file name generated by your build)
ARG JAR_FILE=build/libs/dlb-user-0.0.1-SNAPSHOT.jar

# Add the application's JAR file to the container
#ADD ${JAR_FILE} dlb-user-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} dlb-user.jar

# Environment variable for the Spring profile
ENV SPRING_PROFILES_ACTIVE=dev

# Run the JAR file
ENTRYPOINT ["java","-jar","/dlb-user.jar"]
