apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
  namespace: user-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
        - name: user-server
          image: sodasu/dlb-user
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-server
  namespace: user-namespace
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: user-server